services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres_docker_all
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_docker_all
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

